version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  build:
    commands:
      - echo Building the Go code ..
      - ls -l
      - go get github.com/gin-gonic/gin
      - go build application.go 